name: adaptivetemperaturerecsys
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - matplotlib
  - python-dotenv
  - mlflow
  - datasets
  - polars
  - ipykernel
  - jupyter
  - kaggle
  - pip
  - pip:
      - torch>=2.10.0
      - torchvision
      - -e ./yambdadataset
      - -e ./sasrec/model
      - -e ./sasrec
      - -e .
