[project]
name = "adaptivetemperaturerecsys"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dataset",
    "datasets>=4.5.0",
    "pandas>=3.0.0",
    "torch>=2.10.0",
]

[tool.uv.workspace]
members = [
    "dataset",
]

[tool.uv.sources]
dataset = { workspace = true }
